# Generated by Django 4.2.23 on 2026-01-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('branding_text', models.CharField(blank=True, default='Verwaltung von Schadenmeldungen und Buchungen', max_length=200)),
                ('default_daily_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('default_currency', models.CharField(default='CHF', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portal Einstellung',
                'verbose_name_plural': 'Portal Einstellungen',
            },
        ),
    ]
