# Generated by Django 4.2.23 on 2026-01-20 15:59

import adminportal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0007_portalsettings_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalsettings',
            name='damage_parts',
            field=models.JSONField(blank=True, default=adminportal.models.PortalSettings._default_damage_parts),
        ),
        migrations.AlterField(
            model_name='portalsettings',
            name='damage_types',
            field=models.JSONField(blank=True, default=adminportal.models.PortalSettings._default_damage_types),
        ),
        migrations.AlterField(
            model_name='portalsettings',
            name='insurers',
            field=models.JSONField(blank=True, default=adminportal.models.PortalSettings._default_insurers),
        ),
    ]
