# Generated by Codex on 2026-01-20

import adminportal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminportal", "0008_alter_portalsettings_damage_parts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalsettings",
            name="homepage_services",
            field=models.JSONField(blank=True, default=adminportal.models.PortalSettings._default_homepage_services),
        ),
    ]
