# Generated by Django 4.2.23 on 2026-01-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0009_portalsettings_homepage_services'),
    ]

    operations = [
    ]
