# Generated by Django 4.2.23 on 2026-10-07 15:52

import adminportal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0012_portalsettings_rental_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalsettings',
            name='rental_extras',
            field=models.JSONField(blank=True, default=adminportal.models.PortalSettings._default_rental_extras),
        ),
    ]
