# Generated by Django 4.2.23 on 2025-08-30 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DamageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "car_part",
                    models.CharField(
                        choices=[
                            ("front_bumper", "Frontstossstange"),
                            ("rear_bumper", "Heckstossstange"),
                            ("hood", "Motorhaube"),
                            ("door_left", "Linke Tür"),
                            ("door_right", "Rechte Tür"),
                            ("roof", "Dach"),
                            ("trunk", "Kofferraumdeckel"),
                            ("other", "Sonstiges"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DamagePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="damage_photos/")),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="main.damagereport",
                    ),
                ),
            ],
        ),
    ]
