# Generated by Django 4.2.23 on 2025-09-04 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_transporter_booking"),
    ]

    operations = [
        migrations.RemoveField(model_name="transporter", name="description",),
        migrations.RemoveField(model_name="transporter", name="image",),
        migrations.AddField(
            model_name="transporter",
            name="buchung",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vormittag", "Vormittag"),
                    ("nachmittag", "Nachmittag"),
                    ("ganztag", "Ganztag"),
                ],
                help_text="Verfügbare Buchungsoption",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transporter",
            name="kennzeichen",
            field=models.CharField(default="TEMP-0001", max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transporter",
            name="verfuegbar_ab",
            field=models.DateField(default=datetime.date(2025, 9, 4)),
            preserve_default=False,
        ),
    ]
