# Generated by Django 4.2.23 on 2025-09-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_transporter_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transporter",
            name="bild",
            field=models.ImageField(
                blank=True,
                help_text="Bild des Transporters hochladen",
                null=True,
                upload_to="transporter_bilder/",
            ),
        ),
    ]
