# Generated by Django 4.2.23 on 2025-10-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_transporter_bild"),
    ]

    operations = [
        migrations.AddField(
            model_name="damagereport",
            name="insurer",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Allianz Suisse", "Allianz Suisse"),
                    ("AXA", "AXA"),
                    ("Baloise", "Baloise"),
                    ("Mobiliar", "Die Mobiliar"),
                    ("Generali", "Generali"),
                    ("Helvetia", "Helvetia"),
                    ("Zurich", "Zurich"),
                    ("Vaudoise", "Vaudoise"),
                    ("TCS", "TCS"),
                    ("Simpego", "Simpego"),
                    ("Smile", "Smile"),
                    ("PostFinance", "PostFinance"),
                    ("OTHER", "Andere"),
                    ("NO_INSURANCE", "Ohne Versicherung melden"),
                ],
                max_length=40,
                verbose_name="Versicherung",
            ),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="no_plate",
            field=models.BooleanField(
                default=False, verbose_name="Kontrollschild nicht bekannt"
            ),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="other_insurer",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Andere Versicherung"
            ),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="plate",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="Kontrollschild"
            ),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="policy_number",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Policennummer"
            ),
        ),
        migrations.AlterField(
            model_name="damagereport",
            name="car_part",
            field=models.CharField(
                choices=[
                    ("FRONT_BUMPER", "Frontstossstange"),
                    ("REAR_BUMPER", "Heckstossstange"),
                    ("LEFT_DOOR", "Linke Tür"),
                    ("RIGHT_DOOR", "Rechte Tür"),
                    ("HOOD", "Motorhaube"),
                    ("TRUNK", "Heckklappe"),
                    ("FENDER_FL", "Kotflügel vorne links"),
                    ("FENDER_FR", "Kotflügel vorne rechts"),
                    ("ROOF", "Dach"),
                    ("OTHER", "Sonstiges"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="damagereport",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="damagereport",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="damagereport",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
