# Generated by Django 4.2.23 on 2025-10-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_damagereport_insurer_damagereport_no_plate_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="damagereport", name="name",),
        migrations.AddField(
            model_name="damagereport",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Firmenname"
            ),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="Vorname"
            ),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="Nachname"
            ),
        ),
    ]
