# Generated by Django 4.2.23 on 2025-10-29 18:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_damagereport_name_damagereport_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="damagephoto",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="damagereport",
            name="accident_number",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Schaden-/Unfallnummer"
            ),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="address",
            field=models.CharField(blank=True, max_length=200, verbose_name="Adresse"),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="car_brand",
            field=models.CharField(blank=True, max_length=80, verbose_name="Automarke"),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="car_model",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Automodell"
            ),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="damaged_parts",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Beschädigte Teile"
            ),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="insurer_contact",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Versicherung Ansprechperson"
            ),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="vin",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Stammnummer (VIN)"
            ),
        ),
        migrations.AddField(
            model_name="transporter",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="damagephoto",
            name="image",
            field=models.ImageField(upload_to="damage_photos/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="damagephoto",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="main.damagereport",
                verbose_name="Zugehöriger Report",
            ),
        ),
        migrations.AlterField(
            model_name="damagereport",
            name="car_part",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FRONT_BUMPER", "Frontstossstange"),
                    ("REAR_BUMPER", "Heckstossstange"),
                    ("LEFT_DOOR", "Linke Tür"),
                    ("RIGHT_DOOR", "Rechte Tür"),
                    ("HOOD", "Motorhaube"),
                    ("TRUNK", "Heckklappe"),
                    ("FENDER_FL", "Kotflügel vorne links"),
                    ("FENDER_FR", "Kotflügel vorne rechts"),
                    ("ROOF", "Dach"),
                    ("OTHER", "Sonstiges"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["transporter", "date"], name="main_bookin_transpo_a13614_idx"
            ),
        ),
    ]
