# Generated by Django 4.2.5 on 2025-11-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_damagephoto_uploaded_at_damagereport_accident_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transporter",
            name="farbe",
            field=models.CharField(blank=True, max_length=50, verbose_name="Farbe"),
        ),
        migrations.AddField(
            model_name="transporter",
            name="preis_chf",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=7, verbose_name="Preis (CHF)"
            ),
        ),
    ]
