# Generated by Django 4.2.5 on 2025-11-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_transporter_farbe_transporter_preis_chf"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="additional_insurance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="additional_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="hand_truck",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="moving_blankets",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="tie_down_straps",
            field=models.BooleanField(default=False),
        ),
    ]
