# Generated by Django 4.2.5 on 2025-11-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_booking_additional_insurance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                choices=[("CARD", "Kreditkarte (Stripe)"), ("CASH", "Barzahlung")],
                default="CASH",
                max_length=10,
            ),
        ),
    ]
