# Generated by Django 4.2.5 on 2025-11-28 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_booking_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="customer_address",
            field=models.CharField(default=1, max_length=255, verbose_name="Adresse"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="driver_license_number",
            field=models.CharField(
                default="", max_length=100, verbose_name="Führerscheinnummer"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="customer_phone",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="time_slot",
            field=models.CharField(
                choices=[
                    ("MORNING", "Vormittag"),
                    ("AFTERNOON", "Nachmittag"),
                    ("FULLDAY", "Ganzer Tag"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="transporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.transporter"
            ),
        ),
    ]
