# Generated by Django 4.2.23 on 2026-01-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_booking_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('confirmed', 'Bestätigt'), ('completed', 'Abgeschlossen'), ('cancelled', 'Storniert')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('in_progress', 'In Bearbeitung'), ('completed', 'Abgeschlossen')], default='pending', max_length=20),
        ),
    ]
