# Generated by Django 4.2.23 on 2026-01-05 14:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_booking_admin_notes_booking_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('rental', 'Transporter-Buchung'), ('damage-report', 'Schadenmeldung'), ('manual', 'Manuell'), ('both', 'Beides')], default='manual', max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('customer_since', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('small', 'Sprinter Klein'), ('medium', 'Sprinter Mittel'), ('large', 'Sprinter Gross')], max_length=10)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('volume', models.DecimalField(blank=True, decimal_places=1, help_text='m³', max_digits=5, null=True)),
                ('payload', models.PositiveIntegerField(blank=True, help_text='kg', null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('vin', models.CharField(blank=True, max_length=32)),
                ('insurance_number', models.CharField(blank=True, max_length=64)),
                ('next_service', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Verfügbar'), ('rented', 'Vermietet'), ('maintenance', 'In Wartung'), ('out-of-service', 'Außer Betrieb')], default='available', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicle_photos/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='extras',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance',
            field=models.CharField(choices=[('basic', 'Basis'), ('full', 'Vollkasko'), ('premium', 'Premium')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='km_package',
            field=models.CharField(choices=[('100km', '100 km'), ('200km', '200 km'), ('unlimited', 'Unbegrenzt')], default='100km', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Offen'), ('paid', 'Bezahlt'), ('refunded', 'Erstattet')], default='unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_time',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='accident_date',
            field=models.DateField(blank=True, null=True, verbose_name='Unfalldatum'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='accident_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Unfallort'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='affected_parts',
            field=models.JSONField(blank=True, default=list, verbose_name='Betroffene Teile'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='damage_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Schadensart'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='first_registration',
            field=models.DateField(blank=True, null=True, verbose_name='Erstzulassung'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometerstand'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='other_party_involved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='police_involved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Offen'), ('paid', 'Bezahlt'), ('overdue', 'Überfällig'), ('cancelled', 'Storniert')], default='unpaid', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=30)),
                ('type', models.CharField(choices=[('damage-report', 'Schadenmeldung'), ('rental', 'Vermietung'), ('other', 'Sonstiges')], default='other', max_length=20)),
                ('related_id', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('public_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='main.customer')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='main.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='main.vehicle'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports', to='main.customer'),
        ),
    ]
