# Generated by Django 4.2.23 on 2026-01-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_damagephoto_file_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damagephoto',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
