# Generated by Django 4.2.23 on 2026-01-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_damagephoto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='insurer_contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Mail Kontaktperson'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='insurer_contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon Kontaktperson'),
        ),
    ]
