# Generated by Django 4.2.23 on 2026-01-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_damagereport_insurer_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='type_certificate_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='Typenscheinnummer'),
        ),
    ]
