# Generated by Django 4.2.23 on 2026-01-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_damagereport_type_certificate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='registration_document',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_docs/%Y/%m/%d/', verbose_name='Fahrzeugausweis'),
        ),
    ]
