# Generated by Django 4.2.23 on 2026-01-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_damagereport_registration_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver_license_photo',
            field=models.FileField(blank=True, null=True, upload_to='license_photos/%Y/%m/%d/', verbose_name='Führerscheinfoto'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='driver_license_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Führerscheinnummer'),
        ),
    ]
