# Generated by Django 4.2.23 on 2026-01-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_damagereport_admin_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('INVOICE', 'Rechnung'), ('CASH', 'Bar'), ('TRANSFER', 'Überweisung')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('confirmed', 'Bestätigt'), ('active', 'In Vermietung'), ('completed', 'Abgeschlossen'), ('cancelled', 'Storniert')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='assigned_mechanic',
            field=models.CharField(blank=True, max_length=120, verbose_name='Zugewiesener Mechaniker'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='estimated_cost_chf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kostenschätzung (CHF)'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='repair_end',
            field=models.DateField(blank=True, null=True, verbose_name='Reparaturende'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='repair_start',
            field=models.DateField(blank=True, null=True, verbose_name='Reparaturbeginn'),
        ),
    ]
